# Generated by Django 3.2.7 on 2021-09-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.TextField()),
                ('file_content', models.ManyToManyField(blank=True, null=True, related_name='file_content', to='imgapp.TweetFile')),
            ],
            options={
                'verbose_name_plural': 'Tweets',
            },
        ),
    ]
