# Generated by Django 3.2.7 on 2021-09-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImgFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='images')),
                ('file_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imgapp.posts')),
            ],
        ),
    ]
